const state={paused:false,filter:"ALL",selectedId:"pondy",tick:0,launches:84,pnl:1284.6,tokens:[
{id:"pondy",symbol:"$PONDY",name:"Pond Yield",source:"@greenwhale",age:"18s ago",price:"$0.0386",liq:"$420k",change:"+18.4%",score:86,decision:"TONGUE",reasonTitle:"High-conviction flow",reason:"Hunter entry confirmed with depth and momentum aligned.",walls:[91,78,84,88,89],wallState:["good","good","good","good","good"]},
{id:"moss",symbol:"$MOSS",name:"Moss Protocol",source:"@frogfather",age:"31s ago",price:"$0.0124",liq:"$188k",change:"+9.8%",score:74,decision:"TONGUE",reasonTitle:"Momentum is early",reason:"Two hunter buys landed before the liquidity expansion.",walls:[77,68,83,71,72],wallState:["good","warn","good","good","good"]},
{id:"lilypad",symbol:"$LILY",name:"Lily Pad",source:"@pondwhale",age:"44s ago",price:"$0.0712",liq:"$690k",change:"+5.1%",score:68,decision:"SKIP",reasonTitle:"Wait for the turn",reason:"Price is extended; turn confirmation has not printed yet.",walls:[73,81,42,79,66],wallState:["good","good","bad","good","warn"]},
{id:"croak",symbol:"$CROAK",name:"Croak Labs",source:"@greenwhale",age:"1m ago",price:"$0.0048",liq:"$302k",change:"+22.6%",score:89,decision:"TONGUE",reasonTitle:"Hunter swarm detected",reason:"Three tracked wallets entered inside the same 90s window.",walls:[94,89,91,86,87],wallState:["good","good","good","good","good"]},
{id:"swamp",symbol:"$SWAMP",name:"Swamp Signal",source:"@slowburn",age:"1m ago",price:"$0.0201",liq:"$96k",change:"-3.2%",score:39,decision:"SKIP",reasonTitle:"Depth is too thin",reason:"Liquidity is below the configured paper-entry floor.",walls:[62,31,70,45,54],wallState:["warn","bad","good","bad","warn"]},
{id:"reed",symbol:"$REED",name:"Reed Finance",source:"@quietalpha",age:"2m ago",price:"$0.0289",liq:"$510k",change:"+11.1%",score:81,decision:"TONGUE",reasonTitle:"Clean market structure",reason:"Price reclaim and wallet flow agree on the same direction.",walls:[85,77,76,83,82],wallState:["good","good","good","good","good"]},
{id:"toad",symbol:"$TOAD",name:"Toadstool",source:"@exitliquidity",age:"2m ago",price:"$0.0081",liq:"$274k",change:"+2.2%",score:57,decision:"SKIP",reasonTitle:"No edge after slippage",reason:"Expected move is smaller than the paper slippage buffer.",walls:[59,67,51,62,47],wallState:["warn","good","bad","warn","bad"]},
{id:"ponds",symbol:"$PONDS",name:"Pond Systems",source:"@triplefrog",age:"3m ago",price:"$0.0167",liq:"$346k",change:"+14.6%",score:83,decision:"TONGUE",reasonTitle:"Flow is accelerating",reason:"Buy-side volume and source PnL are both expanding.",walls:[83,76,88,81,86],wallState:["good","good","good","good","good"]}],
hunters:[{name:"@greenwhale",tag:"SHADOW",asset:"$PONDY",pnl:"+18.4%",bars:"3,18 26,38 22,54 29,73 18,89 21,108 10"},{name:"@frogfather",tag:"SHADOW",asset:"$MOSS",pnl:"+9.8%",bars:"3,29 24,24 43,27 60,16 78,22 94,14 108,10"},{name:"@pondwhale",tag:"SHADOW",asset:"$LILY",pnl:"+5.1%",bars:"3,8 20,13 39,12 55,18 72,14 89,22 108,20"},{name:"@quietalpha",tag:"PAPER",asset:"$REED",pnl:"+11.1%",bars:"3,26 20,20 35,24 51,14 68,18 86,8 108,12"}],
positions:[{symbol:"$CROAK",name:"Croak Labs",entry:"$0.0039",mark:"$0.0048",pnl:"+22.6%",rules:"TP 30% · SL 8% · trail 6%",state:"MARKING"},{symbol:"$REED",name:"Reed Finance",entry:"$0.0261",mark:"$0.0289",pnl:"+10.7%",rules:"TP 24% · SL 7% · trail 5%",state:"MARKING"},{symbol:"$PONDY",name:"Pond Yield",entry:"$0.0379",mark:"$0.0386",pnl:"+1.8%",rules:"TP 20% · SL 6% · 45m max",state:"ARMED"}],
events:[["10:57:24","TONGUE","$PONDY  /  @greenwhale entry","+18.4%"],["10:57:20","SCAN","$CROAK  /  5 walls re-scored","89/100"],["10:57:12","SKIP","$SWAMP  /  depth below floor","39/100"],["10:57:05","MOVE","$REED   /  paper mark updated","+10.7%"],["10:56:49","NEW","$LILY   /  fresh launch detected","+5.1%"],["10:56:38","SYNC","hunter pool rotated under radar","12 live"]]};
const $=selector=>document.querySelector(selector);const tokenList=$("#tokenList");
function selectedToken(){return state.tokens.find(token=>token.id===state.selectedId)||state.tokens[0]}
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
function renderTokens(){const visible=state.tokens.filter(token=>state.filter==="ALL"||token.decision===state.filter);tokenList.innerHTML=visible.map(token=>`<div class="token-row ${token.id===state.selectedId?"selected":""}" data-id="${token.id}" tabindex="0" role="button" aria-label="Inspect ${token.symbol}"><div><span class="token-symbol">${escapeHTML(token.symbol)}</span><span class="token-name">${escapeHTML(token.name)}</span><span class="token-source">${escapeHTML(token.source)} · ${escapeHTML(token.age)}</span></div><div class="token-value">${escapeHTML(token.price)}<small>entry</small></div><div class="token-liq">${escapeHTML(token.liq)}<small>liquidity</small></div><div class="token-value ${token.change.startsWith("+")?"up":"down"}">${escapeHTML(token.change)}<small>move</small></div><span class="status-badge ${token.decision.toLowerCase()}">${token.decision}</span></div>`).join("");tokenList.querySelectorAll(".token-row").forEach(row=>{row.addEventListener("click",()=>{state.selectedId=row.dataset.id;renderAll()});row.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();state.selectedId=row.dataset.id;renderAll()}})});const tongue=state.tokens.filter(token=>token.decision==="TONGUE").length;$("#allCount").textContent=state.tokens.length;$("#tongueCount").textContent=tongue;$("#skipCount").textContent=state.tokens.length-tongue}
function renderDecision(){const token=selectedToken();$("#selectedName").textContent=token.symbol;$("#selectedSource").textContent=token.source;$("#selectedAge").textContent=`· ${token.age}`;$("#selectedDecision").textContent=token.decision;$("#selectedDecision").className=`decision-badge ${token.decision.toLowerCase()}`;$("#selectedScore").textContent=token.score;$("#scoreFill").style.width=`${token.score}%`;$("#reasonTitle").textContent=token.reasonTitle;$("#reasonText").textContent=token.reason;$("#selectedPrice").textContent=token.price;$("#selectedLiquidity").textContent=token.liq;$("#reasonBox").classList.toggle("bad",token.decision==="SKIP");$(".reason-icon").textContent=token.decision==="SKIP"?"×":"✓";const button=$("#decisionButton");button.innerHTML=token.decision==="TONGUE"?`Open paper sniper <kbd>SPACE</kbd>`:`Why not this setup <span>↗</span>`;$("#chartName").textContent=`${token.symbol} / USDC`;$("#chartChange").textContent=token.change;$("#chartChange").className=token.change.startsWith("+")?"up":"down";$("#wallGrid").innerHTML=token.walls.map((score,index)=>`<div class="wall ${token.wallState[index]}"><div class="wall-score">${score}</div><div class="wall-key">${["EDGE","DEPTH","TURN","MOMO","PRICE"][index]}</div></div>`).join("");drawChart(token)}
function drawChart(token){const svg=$("#chart");const seed=token.score+state.tick*2;const values=Array.from({length:19},(_,index)=>34+Math.sin(index*.76+seed)*12+index*(token.decision==="SKIP"?.4:1.8)+((index*17+seed)%9));const points=values.map((value,index)=>`${index*28.8},${150-value}`).join(" ");const area=`0,150 ${points} 518,150`;svg.innerHTML=`<defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#20d477" stop-opacity=".28"/><stop offset="1" stop-color="#20d477" stop-opacity="0"/></linearGradient></defs><path class="chart-grid-line" d="M0 35H520M0 78H520M0 121H520"/><polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${points}"/><circle class="chart-dot" cx="518" cy="${150-values[values.length-1]}" r="4"/>`}
function renderHunters(){$("#hunterList").innerHTML=state.hunters.map(hunter=>`<div class="hunter-card"><div class="hunter-line"><span class="hunter-name">${escapeHTML(hunter.name)}</span><span class="hunter-badge">${escapeHTML(hunter.tag)}</span></div><div class="hunter-asset">${escapeHTML(hunter.asset)} <span class="hunter-pnl">${escapeHTML(hunter.pnl)}</span></div><svg class="spark" viewBox="0 0 110 35" preserveAspectRatio="none"><polyline points="${escapeHTML(hunter.bars)}" fill="none" stroke="#20d477" stroke-width="2"/></svg></div>`).join("")}
function renderPositions(){$("#positionsBody").innerHTML=state.positions.map(position=>`<tr><td class="asset-cell">${escapeHTML(position.symbol)}<small>${escapeHTML(position.name)}</small></td><td>${escapeHTML(position.entry)}</td><td>${escapeHTML(position.mark)}</td><td class="up">${escapeHTML(position.pnl)}</td><td class="exit-rules">${escapeHTML(position.rules)}</td><td class="state">● ${escapeHTML(position.state)}</td></tr>`).join("")}
function renderEvents(){$("#eventFeed").innerHTML=state.events.slice(0,7).map(([time,type,message,value])=>`<div class="event-row ${type==="SKIP"?"skip":""}"><span class="event-time">${time.slice(3)}</span><span class="event-type">${type}</span><span class="event-copy">${escapeHTML(message)}</span><span class="event-pnl">${escapeHTML(value)}</span></div>`).join("")}
function renderAll(){renderTokens();renderDecision();renderHunters();renderPositions();renderEvents()}
function toast(message){const node=$("#toast");node.textContent=message;node.classList.add("show");window.clearTimeout(toast.timer);toast.timer=window.setTimeout(()=>node.classList.remove("show"),2600)}
function openPaperSniper(){const token=selectedToken();if(token.decision==="SKIP"){toast(`${token.symbol}: SKIP — ${token.reason.toLowerCase()}`);return}if(state.positions.some(position=>position.symbol===token.symbol)){toast(`${token.symbol} is already marked in paper mode.`);return}state.positions.unshift({symbol:token.symbol,name:token.name,entry:token.price,mark:token.price,pnl:"+0.0%",rules:"TP 20% · SL 6% · 45m max",state:"ARMED",ticks:0,best:0});state.events.unshift(["10:57:32","COPY",`${token.symbol} / paper sniper armed`,`0.0%`]);renderPositions();renderEvents();toast(`${token.symbol} paper sniper armed — exits are automatic.`)}
function rotateHunters(){state.hunters.push(state.hunters.shift());renderHunters();state.events.unshift(["10:57:34","SYNC","hunter pool rotated under radar","12 live"]);renderEvents();toast("Hunter pool rotated under the freshest launches.")}
function refreshRadar(){state.tick+=1;state.launches+=1;$("#launchCount").textContent=state.launches;$("#lastSync").textContent="synced just now";renderDecision();state.events.unshift(["10:57:36","NEW","$FROG    / fresh launch detected","+0.0%"]);renderEvents();toast("Radar refreshed — new launch added to the stream.")}
document.querySelectorAll(".filter").forEach(button=>button.addEventListener("click",()=>{state.filter=button.dataset.filter;document.querySelectorAll(".filter").forEach(item=>item.classList.toggle("active",item===button));renderTokens()}));$("#paperButton").addEventListener("click",openPaperSniper);$("#decisionButton").addEventListener("click",openPaperSniper);$("#rotateButton").addEventListener("click",rotateHunters);$("#refreshButton").addEventListener("click",refreshRadar);$("#pauseButton").addEventListener("click",()=>{state.paused=!state.paused;$("#pauseButton").textContent=state.paused?"▶":"Ⅱ";$("#modeLabel").textContent=state.paused?"SCANNER PAUSED":"LIVE SCANNER";toast(state.paused?"Scanner paused.":"Scanner resumed.")});document.addEventListener("keydown",event=>{if(event.target.matches("input, textarea, select"))return;if(event.code==="Space"){event.preventDefault();openPaperSniper()}if(event.key.toLowerCase()==="p")$("#pauseButton").click();if(event.key.toLowerCase()==="r")refreshRadar();if(event.key.toLowerCase()==="f"){const next=state.filter==="ALL"?"TONGUE":state.filter==="TONGUE"?"SKIP":"ALL";document.querySelector(`[data-filter="${next}"]`).click()}});
window.setInterval(()=>{if(state.paused)return;state.tick+=1;state.tokens.forEach((token,index)=>{const wobble=Math.sin((state.tick+index)*.7)*.8;token.score=Math.max(25,Math.min(97,Math.round(token.score+wobble)))});const closed=[];state.positions.forEach((position,index)=>{position.ticks=(position.ticks||0)+1;const current=parseFloat(position.pnl)||0;const next=current+Math.sin((state.tick+index)*.8)*.55+.18;position.best=Math.max(position.best||0,next);position.pnl=`${next>=0?"+":""}${next.toFixed(1)}%`;position.state="MARKING";const trailing=(position.best-next>=6&&position.best>8);const takeProfit=next>=20;const stopLoss=next<=-6;const maxHold=position.ticks>=34;if(takeProfit||stopLoss||trailing||maxHold){const reason=takeProfit?"TP":stopLoss?"SL":trailing?"TRAIL":"MAX-HOLD";closed.push({position,reason})}});if(closed.length){state.positions=state.positions.filter(position=>!closed.some(item=>item.position===position));closed.forEach(({position,reason})=>state.events.unshift(["10:57:40","EXIT",`${position.symbol} / ${reason} auto-close`,position.pnl]))}const tongue=state.tokens.filter(token=>token.decision==="TONGUE").length;$("#tongueRate").textContent=`${(tongue/state.tokens.length*100).toFixed(1)}%`;$("#lastSync").textContent=`synced ${state.tick%5+1}s ago`;$("#paperPnl").textContent=`${state.pnl>=0?"+":"-"}$${Math.abs(state.pnl).toFixed(2)}`;drawChart(selectedToken());renderPositions();renderEvents()},2600);renderAll();
